apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: client-gateway-container
          image: client-gateway:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_QUEUE
              value: orders_queue
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-manager
spec:
  selector:
    matchLabels:
      app: order-manager
  serviceName: "order-manager"
  replicas: 1
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager-container
          image: order-manager:latest
          ports:
            - containerPort: 4000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_QUEUE
              value: orders_queue
            - name: RABBITMQ_OUT_QUEUE
              value: processed_orders_queue
          volumeMounts:
            - name: order-manager-storage
              mountPath: /data
      volumes:
        - name: order-manager-storage
          persistentVolumeClaim:
            claimName: order-manager-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: market-data-publisher
spec:
  selector:
    matchLabels:
      app: market-data-publisher
  serviceName: "market-data-publisher"
  replicas: 1
  template:
    metadata:
      labels:
        app: market-data-publisher
    spec:
      containers:
        - name: market-data-publisher-container
          image: market-data-publisher:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_QUEUE
              value: processed_orders_queue
          volumeMounts:
            - name: mdp-storage
              mountPath: /data
      volumes:
        - name: mdp-storage
          persistentVolumeClaim:
            claimName: mdp-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: client-gateway-service
spec:
  selector:
    app: client-gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager-service
spec:
  selector:
    app: order-manager
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-publisher-service
spec:
  selector:
    app: market-data-publisher
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-manager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5673
      targetPort: 5672
    - port: 15673
      targetPort: 15672
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-manager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: order-manager
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: market-data-publisher-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: market-data-publisher
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
