services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672" # AMQP port for RabbitMQ consumers/producers
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  client_order_streamer:
    build: ./client_order_streamer
    depends_on:
      rabbitmq:
        condition: service_healthy # Wait for RabbitMQ to be healthy
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    restart: on-failure   # Restarts only if the container exits with a non-zero status
    volumes:
      - ./client_order_streamer/data:/app/data

  client_gateway:
    build: ./client_gateway
    depends_on:
      rabbitmq:
        condition: service_healthy # Wait for RabbitMQ to be healthy
    environment:
      - RABBITMQ_URLL=amqp://rabbitmq:5672
    restart: on-failure   # Restarts only if the container exits with a non-zero status

  order_manager:
    build: ./order_manager
    depends_on:
      rabbitmq:
        condition: service_healthy # Wait for RabbitMQ to be healthy
    environment:
      - RABBITMQ_URLL=amqp://rabbitmq:5672
    restart: on-failure   # Restarts only if the container exits with a non-zero status
    volumes:
      - ./matching-engine:/app/matching-engine  # Mount matching-engine folder