apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: client-gateway-container
          image: client-gateway:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service  # Use the service name
            - name: RABBITMQ_PORT
              value: "5673" 
            - name: RABBITMQ_ORDER_QUEUE
              value: orders  
            - name: RABBITMQ_MANAGER_QUEUE
              value: order_manager_queue
          resources:
            limits:
              cpu: 350m
              memory: 128M
            requests:
              cpu: 200m
              memory: 80M
---
apiVersion: v1
kind: Service
metadata:
  name: client-gateway-service
spec:
  selector:
    app: client-gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP