apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-publisher
spec:
  selector:
    matchLabels:
      app: market-data-publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: market-data-publisher
    spec:
      containers:
        - name: market-data-publisher-container
          image: market-data-publisher:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service  # Use the service name
            - name: RABBITMQ_PORT
              value: "5672" 
            - name: RABBITMQ_ORDERBOOK_QUEUE
              value: orderbook_queue  
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-publisher-service
spec:
  selector:
    app: market-data-publisher
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer      
