apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-manager
spec:
  serviceName: "order-manager-service"
  replicas: 1
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager-container
          image: order-manager:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service  # Use the service name
            - name: RABBITMQ_PORT
              value: "5673"
            - name: RABBITMQ_ORDERBOOK_QUEUE
              value: orderbook_queue
            - name: RABBITMQ_MANAGER_QUEUE
              value: order_manager_queue
          volumeMounts:
            - name: order-data-volume
              mountPath: /app/data  # Mount the volume to the app's directory

  volumeClaimTemplates:
    - metadata:
        name: order-data-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi  # Define the size of the persistent volume (adjust as needed)
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager-service
spec:
  selector:
    app: order-manager
  type: ClusterIP
  ports:
    - port: 9999            # The port exposed by the service inside the cluster
      targetPort: 9999       # The port the container listens on 
      protocol: TCP
