apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  selector:
    matchLabels:
      app: order-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager-container
          imagePullPolicy: Never
          image: order-manager:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service  # Use the service name
            - name: RABBITMQ_PORT
              value: "5672" 
            - name: RABBITMQ_ORDERBOOK_QUEUE
              value: orderbook_queue  
            - name: RABBITMQ_MANAGER_QUEUE
              value: order_manager_queue
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager-service
spec:
  selector:
    app: order-manager
  type: ClusterIP
  ports:
    - port: 9999            # The port exposed by the service inside the cluster
      targetPort: 9999       # The port the container listens on 
      protocol: TCP
