apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
  labels:
    app: client-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-gateway
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: client-gateway
          image: client-gateway:latest
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"  # Use the internal service name for RabbitMQ if it's within the cluster
            - name: RABBITMQ_QUEUE
              value: "orders"
            - name: ORDER_MANAGER_QUEUE
              value: "order_manager_queue"
          resources:
            requests:
              memory: "80M"
              cpu: "200m"
            limits:
              memory: "128M"
              cpu: "350m"
---
apiVersion: v1
kind: Service
metadata:
  name: client-gateway-service
spec:
  selector:
    app: client-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP